#!/bin/bash
# author: gnanaraj.mauviel


echo "_____________________________
        GIT AUTOMATION         
_____________________________"

echo ""
#Pulling the latest code from the branch before making any changes...
echo -e "[+]Pulling the branch";
    read -p "[+]Enter the pull branch name: " branch;
    git pull --rebase origin $branch;
    if [ $? -eq 0 ];
    then
        echo -e "Git pull was successful on [$branch]";
    else
        echo -e "Git pull failed! on [$branch]";
    fi

# Adding new changes to the repo
gstatus=`git status --porcelain`

if [ ${#gstatus} -ne 0 ]
then
    echo -e "[+]Printing Git Status"; echo $gstatus
    echo -e "[+]Adding Files to Push";
    git add --all;
    echo -e "[+]Commit Message";
    git commit -m "$gstatus";
    echo -e "[+]Pushing to the branch";
    read -p "[+]Enter the push branch name: " branch;
    git push -u origin $branch --force;
    if [ $? -eq 0 ];
    then
        echo -e "Git push was successful on [$branch]";
    else
        echo -e "Git push failed! on [$branch]";
    fi
fi