#!/bin/bash


echo -e "\nPrinting Git Status \n";
gstatus=`git status --porcelain`

if [ ${#gstatus} -ne 0 ]
then
    echo -e "\n[+]Adding Files to Push\n";
    git add --all
    echo -e "\n[+]Commit Message\n";
    git commit -m "$gstatus"
	git pull --rebase origin main
    echo -e "\n[+]Pushing to branch main \n";
    git push -u origin main --force;
    if [ $? -eq 0 ];
    then
        echo -e "\nGit push was successful\n";
    else
        echo -e "\nGit push failed!.\n";
    fi
fi