#!/bin/bash
# author: gnanaraj.mauviel


echo "_____________________________
        GIT AUTOMATION         
_____________________________"

gstatus=`git status --porcelain`

if [ ${#gstatus} -ne 0 ]
then
    echo -e "[+]Printing Git Status"; echo $gstatus
    echo -e "[+]Adding Files to Push";
    git add --all;
    echo -e "[+]Commit Message";
    git commit -m "$gstatus";
    echo -e "[+]Pulling the branch";
    echo -e "[+]Enter the pull branch name: ";
    read branch;
	git pull --rebase origin $branch;
    if [ $? -eq 0 ];
    then
        echo -e "Git pull was successful on $branch...";
    else
        echo -e "Git pull failed! on $branch...";
    fi
    echo -e "[+]Pushing to the branch";
    echo -e "[+]Enter the push branch name: ";
    read branch;
    git push -u origin $branch --force;
    if [ $? -eq 0 ];
    then
        echo -e "Git push was successful on $branch...";
    else
        echo -e "Git push failed! on $branch...";
    fi
fi